### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aditya-pushkar** [pierreleocadie/ScrapeGram#1]
```
Traceback (most recent call last):
  File "/Users/Desktop/instabot/ScrapeGram/src/main.py", line 1, in <module>
    from Queries import Queries
  File "/Users/Desktop/instabot/ScrapeGram/src/Queries.py", line 1, in <module>
    import requests, json, constants, logging, os
  File "/Users/Desktop/instabot/ScrapeGram/src/constants.py", line 10, in <module>
    os.mkdir(os.path.join("src", "logs"))
```
error while starting the file

**Comment by pierreleocadie** [comment]
Hey ! What is your Python version ? Did you install the requirements (requirements.txt) ? Can you provide more information about your environment ?

**Comment by aditya-pushkar** [comment]
yes, I installed all the requirements and  im using python 3.9.6 and using virtualenv for virtual enviroment, my operating system is mac.

**Comment by aditya-pushkar** [comment]
@pierreleocadie any update ?

**Comment by pierreleocadie** [comment]
I'll take a look and I'll fix it !

**Comment by pierreleocadie** [comment]
@aditya-pushkar I think you must be using Python version 3.10.0 or later. Try it and keep me informed :)

**Comment by aditya-pushkar** [comment]
@pierreleocadie  I'm using Python 3.9.6

**Comment by aditya-pushkar** [comment]
can you run this code on replit.com ?

**Comment by pierreleocadie** [comment]
@aditya-pushkar You can't run it on replit.com, I tried and I can't. I had the same error as you

**Comment by aditya-pushkar** [comment]
@pierreleocadie  what are your python version and operating system?

**Comment by pierreleocadie** [comment]
@aditya-pushkar my python version is 3.10.0 and my operating system is macOS Monterey

**Comment by aditya-pushkar** [comment]
If the bot is running on your system then just containerized it and upload the Dockerfile, I think it is the easiest way.

**Comment by pierreleocadie** [comment]
I'll do it ! Thanks for the idea !

**Comment by aditya-pushkar** [comment]
@pierreleocadie can you able to do it today? it will help me a lot ? thanks

**Comment by pierreleocadie** [comment]
@aditya-pushkar yep but can you try to run main.py from ScrapeGram folder like this :
```bash
cd ScrapeGram
python3 src/main.py #or python src/main.py
```
I think this could solve the problem. Keep me informed
